# Generated by Django 2.0.dev20170912171944 on 2017-09-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JUDO_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField(default='0')),
                ('quantity', models.TextField(default='0')),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game_JUDO',
            },
        ),
        migrations.CreateModel(
            name='ROFR_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CBS_price_1', models.TextField(default='0')),
                ('CBS_price_2', models.TextField(default='0')),
                ('NBC_price_1', models.TextField(default='0')),
                ('NBC_price_2', models.TextField(default='0')),
                ('round_1_step_1', models.BinaryField(default=False)),
                ('round_1_step_2', models.BinaryField(default=False)),
                ('round_2_step_1', models.BinaryField(default=False)),
                ('round_2_step_2', models.BinaryField(default=False)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game_ROFR',
            },
        ),
    ]
