# Generated by Django 2.0.dev20170912171944 on 2017-09-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rofr_model',
            name='round_1_step_1',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='rofr_model',
            name='round_1_step_2',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='rofr_model',
            name='round_2_step_1',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='rofr_model',
            name='round_2_step_2',
            field=models.TextField(default='0'),
        ),
    ]
